name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: '5.x'
      - run: nuget restore Solutions/Solutions.sln
      - uses: microsoft/setup-msbuild@v1
      - run: msbuild Solutions/Solutions.sln -property:Configuration=Release
      - uses: actions/setup-node@v2.3.2
      - run: npm i -g @matrix42/cli
      - run: m42 login -pat ${{ secrets.M42_DEVOPS_PORTAL_PAT }}
      - run: m42 generate-extension -m BasePackage/package.json |
          -o dist/build-${{ github.sha }}.zip |
          -a Solutions/M42ExtensionsGettingStartedBusinessLogic/bin/Release |
          -b ${{ github.run_number }} |
          -om dist/package.json
